### ISSUE TITLE
Remove ava from devDependencies

### ISSUE THREAD

**Issue by ankurk91** [eddyerburgh/vue-test-utils-mocha-example#1]
Hi,
Should we remove `ava` from package.json ?
May be everything related to `ava`.
It may create confusion.

https://github.com/eddyerburgh/vue-test-utils-mocha-example/blob/9c7d4b82902573aa5b8945a028d50a0a601f3614/package.json#L21

**Comment by eddyerburgh** [comment]
Yes definitely, can you make a PR?

**Comment by ankurk91** [comment]
Yup, just few minutes

See PR #2
